version: "3.8"

services:
  mongo:
    image: mongo:6.0
    container_name: prescripto-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: prescripto
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    container_name: prescripto-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://mongo:27017/prescripto
      JWT_SECRET: demo_jwt_secret
      # Demo Razorpay keys
      RAZORPAY_KEY_ID: "rzp_test_1234567890abcdef"
      RAZORPAY_KEY_SECRET: "rzp_test_secret_demo_key"
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: prescripto-frontend
    restart: unless-stopped
    environment:
      REACT_APP_API_URL: http://prescripto-backend:5000
    ports:
      - "3000:80"
    depends_on:
      - backend

  admin:
    build: ./admin
    container_name: prescripto-admin
    restart: unless-stopped
    environment:
      REACT_APP_API_URL: http://prescripto-backend:5000
    ports:
      - "4000:80"
    depends_on:
      - backend

volumes:
  mongo_data:
